import passport from '../config/passportConfig.js';
import User from '../models/User.js';
import ClubPage from '../models/Clubpage.js';

/**
 * @author Lars Andreas Strand
 * @description This function is used to authorize a user and check if they are a member of a club
 * Even if the user is not a member of a club, they will still be authenticated as a user
 */

const checkMemberStatus = (req, res, next) => {
    passport.authenticate('jwt', { session: false }, async (error, user) => {
        if (error) return next(error);
        if (!user) {
            req.user = { role: "user" };
            return next();
        }
        if (req.header("Authorization") === undefined) {
            req.user = { role: "user" };
            return next();
        }

        if (user.role === 'clubowner' || user.role === 'admin') {
            req.user = user;
            return next();
        }

        try {
            const member = await User.findById({ _id: user.id });

            if (!member) {
                req.user = { ...user, role: 'user' };
                return next();
            }

            const isMember = await ClubPage.findOne({ _id: req.params.id, members: member._id });
            req.user = { ...user, role: isMember ? 'member' : 'user' };
            return next();
        } catch (err) {
            return next(err);
        }
    })(req, res, next);
};

/**
 *
 * @author Lars Andreas Strand and Adrian Johansen
 * @description This is a custom middleware meant for allowing access to user roles even in routes where you're not supposed to need authentication.
 * @generated by Copilot AI from a more simple version of the function written by Lars Andreas Strand and Adrian Johansen
 */

const optionalAuth = (req, res, next) => {
    if (req.header("Authorization")) {
        passport.authenticate('jwt', { session: false }, (err, user) => {
            if (err) return next(err);
            req.user = user;
            return next();
        })(req, res, next);
    } else {
        req.user = { role: "user" };
        next();
    }
}

export { checkMemberStatus, optionalAuth };
