import passport from '../config/passportConfig.js';

/**
 * 
 * @author Lars Andreas Strand and Adrian Johansen
 * @description This is a custom middleware meant for allowing access to user roles even in routes where you're not supposed to need authentication.
 * @generated by Copilot AI from a more simple version of the function written by Lars Andreas Strand and Adrian Johansen
 */

const optionalAuth = (req, res, next) => {
    if (req.header("Authorization")) {
        passport.authenticate('jwt', { session: false }, (err, user, info) => {
            if (err) return next(err);
            req.user = user;
            return next();
        })(req, res, next);
    } else {
        req.user = { role: "user" };
        next();
    }
}

export { optionalAuth };
