// layout.tsx
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Footer from '@/components/global/footer'

import '@/i18n';
import i18next from 'i18next'
import { I18nextProvider } from 'react-i18next'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Discgolf App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='no'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nextProvider i18n={i18next}>
          <div className='min-h-screen flex flex-col'>
            <main className='flex-grow'>{children}</main>
          </div>
        </I18nextProvider>
      </body>
    </html>
  )
}
